apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: 
    - /bin/sh
    - -c
    - 'sleep 3600;'
    volumeMounts:
    - name: k8s
      mountPath: /app
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes: 
  - name: k8s
    hostPath:
      path: /etc/kubernetes
status: {}
