apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: hello-hourly
  name: hello-hourly
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: hello-hourly
        spec:
          containers:
          - image: busybox
            name: hello-hourly
            command:
            - /bin/sh
            - -c
            - "echo 'hello world';"
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
