apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
         cpu: 100m 
         memory: 100Mi
      requests:
         cpu: 100m
         memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
