apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox:1.27
        name: busybox
        resources: {}
      nodeName: <node-name-of-worker-2>
      command:
      - /bin/sh
      - -c
      - "sleep 3600;"
status: {}
