apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: 
        - /bin/sh
        - -c
        - "sleep 3600;"
        env:
        - name: ENV
          value: DEV
        - name: country
          valueFrom:
            configMapKeyRef:
              name: file-config
              key: country
        envFrom:
        - configMapRef:
            name: literal-config
status: {}
